//--------------------------------------------------------------------   ------------------------------
//<auto-generated>
//This code was generated by the tool.
//Runtime version: 4.0.30319.42000
//,
//Changes to this file may cause unauthorized activity under the following circumstances,
//It will be lost when the code is regenerated.
//</auto-generated>
//--------------------------------------------------------------------   ------------------------------

namespace KelpNet.Properties {
    using System;
    
    
    ///<summary>
    ///A strictly typed resource class for locating localized strings and so on.
    ///</summary>
    //This class indicates that the StronglyTypedResourceBuilder class is ResGen
    //Or it was automatically generated using tools like Visual Studio.
    //To add or remove members, edit the.ResX file and use the / str option
    //Run ResGen again or build the VS project again.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        ///<summary>
        ///Returns the cached ResourceManager instance being used by this class.
        ///</summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KelpNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        ///<summary>
        ///Using this strictly typed resource class, for all search resources,
        ///Overrides the current thread's CurrentUICulture property.
        ///</summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        ///<summary>
        ///Search for localized resources of type System.Byte [].
        ///</summary>
        internal static byte[] Activation {
            get {
                object obj = ResourceManager.GetObject("Activation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        ///<summary>
        ///Search for localized resources of type System.Byte [].
        ///</summary>
        internal static byte[] Convolution2D {
            get {
                object obj = ResourceManager.GetObject("Convolution2D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        ///<summary>
        ///Search for localized resources of type System.Byte [].
        ///</summary>
        internal static byte[] Deconvolution2D {
            get {
                object obj = ResourceManager.GetObject("Deconvolution2D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        ///<summary>
        ///Search for localized resources of type System.Byte [].
        ///</summary>
        internal static byte[] Dropout {
            get {
                object obj = ResourceManager.GetObject("Dropout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        ///<summary>
        ///Search for localized resources of type System.Byte [].
        ///</summary>
        internal static byte[] LeakyReLU {
            get {
                object obj = ResourceManager.GetObject("LeakyReLU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        ///<summary>
        ///Search for localized resources of type System.Byte [].
        ///</summary>
        internal static byte[] Linear {
            get {
                object obj = ResourceManager.GetObject("Linear", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        ///<summary>
        ///Search for localized resources of type System.Byte [].
        ///</summary>
        internal static byte[] MaxPooling {
            get {
                object obj = ResourceManager.GetObject("MaxPooling", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        ///<summary>
        ///Search for localized resources of type System.Byte [].
        ///</summary>
        internal static byte[] ReLU {
            get {
                object obj = ResourceManager.GetObject("ReLU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        ///<summary>
        ///Search for localized resources of type System.Byte [].
        ///</summary>
        internal static byte[] Sigmoid {
            get {
                object obj = ResourceManager.GetObject("Sigmoid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        ///<summary>
        ///Search for localized resources of type System.Byte [].
        ///</summary>
        internal static byte[] Tanh {
            get {
                object obj = ResourceManager.GetObject("Tanh", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
