//--------------------------------------------------------------------   ------------------------------
//<auto-generated>
//This code was generated by the tool.
//Runtime version: 4.0.30319.42000
//,
//Changes to this file may cause unauthorized activity under the following circumstances,
//It will be lost when the code is regenerated.
//</auto-generated>
//--------------------------------------------------------------------   ------------------------------

namespace KelpNetWaifu2x.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
